# Lab - 01

In [1]:
import numpy as np

## Prog - 01 : Create a Numpy array of size 4 x 5.

In [2]:
myarr = np.array([[3,5,7,4,5],[2,4,5,6,5], [3,5,7,4,5],[2,4,5,6,5]]) 
myarr

array([[3, 5, 7, 4, 5],
       [2, 4, 5, 6, 5],
       [3, 5, 7, 4, 5],
       [2, 4, 5, 6, 5]])

## Prog - 02 : Randomly initialize the array.

In [3]:
myRanArr = np.random.randint(10, size = (3,4))
myRanArr

array([[5, 0, 9, 0],
       [4, 2, 8, 8],
       [6, 3, 9, 2]])

## Prog - 03 : Get the Transpose of the Matrix that you created. Create a square matrix and find its determinant.

In [4]:
tMatrix = myarr.T
tMatrix

array([[3, 2, 3, 2],
       [5, 4, 5, 4],
       [7, 5, 7, 5],
       [4, 6, 4, 6],
       [5, 5, 5, 5]])

In [5]:
mySqrArr = np.random.randint(10, size = (3,3))
print(mySqrArr)
print(np.linalg.det(mySqrArr))

[[3 9 7]
 [7 8 0]
 [0 5 9]]
-105.99999999999997


# Prog - 04 : Create another matrix of size 5 x 4 and randomly initialize it.

In [6]:
myarr2 = np.random.randint(100, size = (5,4))
myarr2

array([[24, 99, 56, 62],
       [10, 12, 17, 84],
       [28, 92, 25,  9],
       [88, 77, 35, 65],
       [24, 61, 14, 53]])

## Prog - 05 : Perform Matrix multiplication.

In [7]:
np.matmul(myarr, myarr2)

array([[ 790, 1614,  638, 1194],
       [ 876, 1473,  585, 1160],
       [ 790, 1614,  638, 1194],
       [ 876, 1473,  585, 1160]])

## Prog - 06 : Perform element wise matrix multiplication.

In [8]:
myarr3 = np.random.randint(10, size = (3,3))
myarr4 = np.random.randint(10, size = (3,3))
print(myarr3)
print(myarr4)
myarr3 * myarr4

[[2 9 2]
 [6 1 6]
 [5 3 9]]
[[5 6 1]
 [6 8 6]
 [1 6 2]]


array([[10, 54,  2],
       [36,  8, 36],
       [ 5, 18, 18]])

## Prog - 07 : Find mean, median of the numpy array created.

In [9]:
myarr5 = np.random.randint(10, size = (3,3))
print(myarr5)
np.median(myarr5)

[[2 1 8]
 [9 4 7]
 [4 6 1]]


4.0

In [10]:
np.mean(myarr5)

4.666666666666667

## Prog - 08 : Obtain each row in the second column of the first array.

In [11]:
myarr[1]

array([2, 4, 5, 6, 5])

## Prog - 09 : Convert Numeric entries(columns) of Iris.csv to Mean Centered Version

In [12]:
from sklearn import datasets
iris = datasets.load_iris()
X = iris.data
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

## Prog - 10 : Study about numpy array attributes and implement it on the first matrix.

In [13]:
np.sqrt(myarr) #gives square-root of each element in array

array([[1.73205081, 2.23606798, 2.64575131, 2.        , 2.23606798],
       [1.41421356, 2.        , 2.23606798, 2.44948974, 2.23606798],
       [1.73205081, 2.23606798, 2.64575131, 2.        , 2.23606798],
       [1.41421356, 2.        , 2.23606798, 2.44948974, 2.23606798]])

In [14]:
print(myarr.sum())
print(myarr.max())
print(myarr.min())
print(np.count_nonzero(myarr)) #counts total nonzero elements

92
7
2
20


In [15]:
myarr.itemsize * myarr.size #total space required by numpy array

160

In [16]:
print(myarr.argmin()) #first makes it straight and then gives index of the minimum value
print(myarr.argmax()) #first makes it straight and then gives index of the maximum value
print(myarr.argsort(axis=0)) #in verticel lines sorts elements by weight and gives it's index
print(myarr.argsort(axis=1)) #in horizontal lines sorts elements by weight and gives it's index

5
2
[[1 1 1 0 0]
 [3 3 3 2 1]
 [0 0 0 1 2]
 [2 2 2 3 3]]
[[0 3 1 4 2]
 [0 1 2 4 3]
 [0 3 1 4 2]
 [0 1 2 4 3]]
