In [ ]:
#Importing libraries
import numpy as np
import pandas as pd
import io
import matplotlib.pyplot as plt

In [ ]:
# reading the csv file, del 2 columns from the file, checking first few rows of the file
from google.colab import files
uploaded = files.upload()
data = pd.read_csv(io.BytesIO(uploaded['BuyComputer.csv']))
# Kdata.drop(columns=['User ID'],axis=1,inplace=True)
data.head()

Saving BuyComputer.csv to BuyComputer (3).csv


User ID  Age  EstimatedSalary  Purchased
0  15624510   19            19000          0
1  15810944   35            20000          0
2  15668575   26            43000          0
3  15603246   27            57000          0
4  15804002   19            76000          0

In [ ]:
# Splitting data
from sklearn.model_selection import train_test_split
X = data.iloc[:, :-1].values
Y = data.iloc[:,-1].values
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.20, random_state = 34)

In [ ]:
# Scaling data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
# Variabes to calculate sigmoid function
y_pred = []
len_x = len(X_train[0])
w = []
b = 0.2
print("len_x : ", len_x)
entries = len(X_train[:,0])
print("entries : ", entries)

len_x :  2
entries :  320


In [ ]:
for weights in range(len_x):
  w.append(0)
w

[0, 0]

In [ ]:
# Sigmoid function
def sigmoid(z):
  pass

In [ ]:
def predict(inputs):
  pass

In [ ]:
# Loss function
def loss_func(y,a):
  J = 0
  return J

In [ ]:
dw = []
db = 0
J = 0
alpha = 0.1
for x in range(len_x):
  dw.append(0)
# Fitting Logistic Regression to the Training set
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(random_state = 0)

In [ ]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(random_state = 0)

Prob - 01

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline
import tensorflow as tf

import numpy as np 
import pandas as pd 
import io
import matplotlib.pyplot as plt

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')
from google.colab import files
uploaded = files.upload()
data = pd.read_csv(io.BytesIO(uploaded['BuyComputer.csv']))
data.drop(columns = ['User ID',], axis = 1,inplace = True)
data.head()

Saving BuyComputer.csv to BuyComputer (5).csv


Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [ ]:
X = data.iloc[:, :-1].values
print("X : ", X)

X :  [[    19  19000]
 [    35  20000]
 [    26  43000]
 [    27  57000]
 [    19  76000]
 [    27  58000]
 [    27  84000]
 [    32 150000]
 [    25  33000]
 [    35  65000]
 [    26  80000]
 [    26  52000]
 [    20  86000]
 [    32  18000]
 [    18  82000]
 [    29  80000]
 [    47  25000]
 [    45  26000]
 [    46  28000]
 [    48  29000]
 [    45  22000]
 [    47  49000]
 [    48  41000]
 [    45  22000]
 [    46  23000]
 [    47  20000]
 [    49  28000]
 [    47  30000]
 [    29  43000]
 [    31  18000]
 [    31  74000]
 [    27 137000]
 [    21  16000]
 [    28  44000]
 [    27  90000]
 [    35  27000]
 [    33  28000]
 [    30  49000]
 [    26  72000]
 [    27  31000]
 [    27  17000]
 [    33  51000]
 [    35 108000]
 [    30  15000]
 [    28  84000]
 [    23  20000]
 [    25  79000]
 [    27  54000]
 [    30 135000]
 [    31  89000]
 [    24  32000]
 [    18  44000]
 [    29  83000]
 [    35  23000]
 [    27  58000]
 [    24  55000]
 [    23  48000]
 [    28  79000]
 [    22 

In [ ]:
Y = data.iloc[:,-1].values
print("Y : ", Y)

Y :  [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 1 1 0 0 0 1 0 0 0 1 0 1
 1 1 0 0 1 1 0 1 1 0 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1 0 0 1
 1 0 1 1 0 1 1 0 0 1 0 0 1 1 1 1 1 0 1 1 1 1 0 1 1 0 1 0 1 0 1 1 1 1 0 0 0
 1 1 0 1 1 1 1 1 0 0 0 1 1 0 0 1 0 1 0 1 1 0 1 0 1 1 0 1 1 0 0 0 1 1 0 1 0
 0 1 0 1 0 0 1 1 0 0 1 1 0 1 1 0 0 1 0 1 0 1 1 1 0 1 0 1 1 1 0 1 1 1 1 0 1
 1 1 0 1 0 1 0 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1]


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.20, random_state = 34)
print("X_train : ", X_train)
print("X_test : ", X_test)
print("y_train : ", y_train)
print("y_test : ", y_test)

X_train :  [[    39  79000]
 [    28  59000]
 [    42  80000]
 [    41  72000]
 [    29  47000]
 [    45  79000]
 [    60  34000]
 [    28  55000]
 [    58  23000]
 [    58  38000]
 [    45  45000]
 [    26  15000]
 [    31  74000]
 [    35  53000]
 [    39  73000]
 [    28  32000]
 [    40  57000]
 [    30 116000]
 [    48  96000]
 [    45  22000]
 [    35  44000]
 [    31  71000]
 [    52  90000]
 [    39  71000]
 [    31  68000]
 [    32 117000]
 [    40  65000]
 [    48  41000]
 [    41  87000]
 [    24  19000]
 [    32  18000]
 [    35  57000]
 [    29  43000]
 [    25  22000]
 [    18  44000]
 [    30  80000]
 [    26  30000]
 [    30  79000]
 [    44  39000]
 [    38  50000]
 [    24  23000]
 [    47 107000]
 [    28  87000]
 [    37  80000]
 [    37  70000]
 [    49  86000]
 [    30  62000]
 [    40 107000]
 [    39  61000]
 [    31  89000]
 [    30  87000]
 [    32 135000]
 [    52 138000]
 [    42 149000]
 [    60 102000]
 [    42  73000]
 [    21  88000]
 [    35  71000]
 [ 

In [ ]:
# Scaling the data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
# calculate sigmoid function
y_pred = []
x_length = len(X_train[0])
w = []
b = 0.2
print("x_length : ", x_length)

x_length :  2


In [ ]:
entries = len(X_train[:,0])
print("entries : ", entries)

entries :  320


In [ ]:
for weights in range(x_length):
    w.append(0)
w

[0, 0]

In [ ]:
# Sigmoid function
def sigmoid(z):
  return 1/(1 + np.exp(-z))

In [ ]:
# Loss function
def loss_func(y, a):
    J = -(y * np.log(a) + (1 - y) * np.log(1 - a))
    return J

In [ ]:
def predict(inputs):
    return sigmoid(np.dot(w, inputs) + b)

In [ ]:
dw = []
db = 0
J = 0
alpha = 0.1
for x in range(x_length):
    dw.append(0)

In [ ]:
# Repeating the process 3000 times
for iterations in range(3500):
    for i in range(entries):
        localx = X_train[i]
        a = predict(localx)
        dz = a - y_train[i]
        J += loss_func(y_train[i], a)
        for j in range(x_length):
            dw[j] = dw[j]+(localx[j]*dz)
        db += dz
    J = J/entries
    db = db/entries
    for x in range(x_length):
        dw[x]=dw[x]/entries
    for x in range(x_length):
        w[x] = w[x]-(alpha*dw[x])
    b = b-(alpha*db)         
    J=0

In [ ]:
# predicting the label
print("bias : ", b)
for x in range(len(y_test)):
    y_pred.append(predict(X_test[x]))

bias :  -1.2215480590803591


In [ ]:
# set actual and predicted values in a table
for x in range(len(y_pred)):
    if y_pred[x] >= 0.5:
        y_pred[x] = 1
    else:
        y_pred[x] = 0

In [ ]:
# Calculating accuracy of prediction
count = 0
for x in range(len(y_pred)):
    if(y_pred[x] == y_test[x]):
        count = count + 1
print('Accuracy:',(count/(len(y_pred))) * 100)

Accuracy: 80.0


Prog - 02

In [ ]:
from __future__ import absolute_import, division, print_function
import matplotlib.pyplot as plt
import tensorflow as tf
%matplotlib inline

import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import io

In [ ]:
from tensorflow.keras.datasets import mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Convert to float32.
x_train = np.array(x_train, np.float32)
x_test = np.array(x_test, np.float32)

# Flatten images to 1-D vector of 784 features (28*28).
num_features=784
x_train = x_train.reshape(60000, num_features)
x_test = x_test.reshape(10000, num_features)

# Normalize images value from [0, 255] to [0, 1].
x_train = x_train / 255
x_test = x_test /255

print("x_train : ", x_train)
print("x_test : ", x_test)

11501568/11490434 [==============================] - 0s 0us/step
x_train :  [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
x_test :  [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
# MNIST dataset parameters.
num_classes = 10 # 0 to 9 digits
num_features = 784 # 28*28
# Training parameters.
learning_rate = 0.01
training_steps = 1000
batch_size = 256
display_step = 50

In [ ]:
# Use tf.data API to shuffle and batch data.
num_batches = int(x_train.shape[0] / batch_size)
train_data = tf.data.Dataset.from_tensor_slices((x_train, y_train))
train_data = train_data.repeat().shuffle(5000).batch(batch_size).prefetch(1)
print("train_data : ", train_data)

train_data :  <PrefetchDataset shapes: ((None, 784), (None,)), types: (tf.float32, tf.uint8)>


In [ ]:
# Weight of shape [784, 10], the 28*28 image features, and a total number of classes.
W = tf.Variable(np.random.randn(784, 10).astype(np.float32))
# Bias of shape [10], the total number of classes.
B = tf.Variable(np.random.randn(10).astype(np.float32))

In [ ]:
# Logistic regression (Wx + b).

def logistic_regression(x):
    # Apply softmax to normalize the logits to a probability distribution.
    return tf.nn.softmax(tf.add(tf.matmul(x, W), B))

# Cross-Entropy loss function.
def cross_entropy(y_pred, y_true):
    # Encode label to a one hot vector.
    y_true = tf.one_hot(y_true, depth = num_classes)
    # Clip prediction values to avoid log(0) error.
    y_pred = tf.clip_by_value(y_pred, 1e-9, 1.)    
    # Compute cross-entropy.
    loss = tf.reduce_mean(-tf.reduce_sum(y_true * tf.math.log(y_pred)))
    return loss

In [ ]:
# Accuracy metric.

def accuracy(y_pred, y_true):
  # Predicted class is the index of the highest score in prediction vector (i.e. argmax).
  correct_prediction = tf.equal(tf.argmax(y_pred, 1), tf.cast(y_true, tf.int64))
  return tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

In [ ]:
# Optimization process. 

optimizer = tf.optimizers.SGD(learning_rate)
def run_optimization(x, y):
# Wrap computation inside a GradientTape for automatic differentiation.
    with tf.GradientTape() as g:
        pred = logistic_regression(x)
        loss = cross_entropy(pred, y)
    # Compute gradients.
    gradients = g.gradient(loss, [W, B])
    # Stochastic gradient descent optimizer.
    # Update W and b following gradients.
    optimizer.apply_gradients(zip(gradients, [W, B]))

In [ ]:
# Run training for the given number of steps.

for step, (batch_x, batch_y) in enumerate(train_data.take(training_steps), 1):
    # Run the optimization to update W and b values.
    run_optimization(batch_x, batch_y)
    if step % display_step == 0:
        #Obtain Predictions
        pred = logistic_regression(batch_x)
        #Ccompute loss
        loss = cross_entropy(pred, batch_y)
        #Compute Accuracy
        acc = accuracy(pred, batch_y)
        #print accuracy
        print(f"step: {step}, loss: {loss}, accuracy: {acc}")

step: 50, loss: 103.88822937011719, accuracy: 0.9140625
step: 100, loss: 126.70921325683594, accuracy: 0.89453125
step: 150, loss: 141.98439025878906, accuracy: 0.890625
step: 200, loss: 178.16412353515625, accuracy: 0.8359375
step: 250, loss: 76.67472839355469, accuracy: 0.91796875
step: 300, loss: 60.393470764160156, accuracy: 0.94921875
step: 350, loss: 86.37206268310547, accuracy: 0.92578125
step: 400, loss: 107.32426452636719, accuracy: 0.91015625
step: 450, loss: 38.09217071533203, accuracy: 0.96875
step: 500, loss: 59.21806335449219, accuracy: 0.953125
step: 550, loss: 55.21485900878906, accuracy: 0.9296875
step: 600, loss: 55.67284393310547, accuracy: 0.94140625
step: 650, loss: 72.01405334472656, accuracy: 0.93359375
step: 700, loss: 53.8112907409668, accuracy: 0.9453125
step: 750, loss: 138.40957641601562, accuracy: 0.875
step: 800, loss: 89.28522491455078, accuracy: 0.87890625
step: 850, loss: 72.9780044555664, accuracy: 0.91796875
step: 900, loss: 81.72396850585938, accurac

In [ ]:
# Test model on validation set.
pred = logistic_regression(x_test)
a = accuracy(pred, y_test)
print(f"Test Accuracy: {a}")

Test Accuracy: 0.9050999879837036
