# Lab_02

## 1. Handling the missing values:

In [1]:
import numpy as np 
import pandas as pd
dataset = pd.read_csv('Exercise-CarData.csv') 
dataset.info()
dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  1436 non-null   int64  
 1   Price       1436 non-null   int64  
 2   Age         1336 non-null   float64
 3   KM          1436 non-null   object 
 4   FuelType    1336 non-null   object 
 5   HP          1436 non-null   object 
 6   MetColor    1286 non-null   float64
 7   Automatic   1436 non-null   int64  
 8   CC          1436 non-null   int64  
 9   Doors       1436 non-null   object 
 10  Weight      1436 non-null   int64  
dtypes: float64(2), int64(5), object(4)
memory usage: 123.5+ KB


Unnamed: 0  Price   Age     KM FuelType   HP  MetColor  Automatic    CC  \
0              0  13500  23.0  46986   Diesel   90       1.0          0  2000   
1              1  13750  23.0  72937   Diesel   90       1.0          0  2000   
2              2  13950  24.0  41711   Diesel   90       NaN          0  2000   
3              3  14950  26.0  48000   Diesel   90       0.0          0  2000   
4              4  13750  30.0  38500   Diesel   90       0.0          0  2000   
...          ...    ...   ...    ...      ...  ...       ...        ...   ...   
1431        1431   7500   NaN  20544   Petrol   86       1.0          0  1300   
1432        1432  10845  72.0     ??   Petrol   86       0.0          0  1300   
1433        1433   8500   NaN  17016   Petrol   86       0.0          0  1300   
1434        1434   7250  70.0     ??      NaN   86       1.0          0  1300   
1435        1435   6950  76.0      1   Petrol  110       0.0          0  1600   

      Doors  Weight  
0     three    1165  
1         3    1165  
2         3    1165  
3         3    1165  
4         3    1170  
...     ...     ...  
1431      3    1025  
1432      3    1015  
1433      3    1015  
1434      3    1015  
1435      5    1114  

[1436 rows x 11 columns]

### **1.1. Handling Missing Values**

In [2]:
db_copy = dataset
db_copy.dropna(axis=0,how='any',inplace=True) #deletes row which has a single NULL value (column if axis=1)
db_copy.info()
#db_copy

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1111 entries, 0 to 1435
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  1111 non-null   int64  
 1   Price       1111 non-null   int64  
 2   Age         1111 non-null   float64
 3   KM          1111 non-null   object 
 4   FuelType    1111 non-null   object 
 5   HP          1111 non-null   object 
 6   MetColor    1111 non-null   float64
 7   Automatic   1111 non-null   int64  
 8   CC          1111 non-null   int64  
 9   Doors       1111 non-null   object 
 10  Weight      1111 non-null   int64  
dtypes: float64(2), int64(5), object(4)
memory usage: 104.2+ KB


### **1.2. Imputation**

**1.2.1. Replacing NULL data with mean() value**

In [3]:
dataset = pd.read_csv('Exercise-CarData.csv') 
dataset.info()
print("Mean for column MetColor is : " + str(dataset['MetColor'].mean()))
dataset['MetColor']=dataset['MetColor'].fillna(dataset['MetColor'].mean())
dataset.info()
#dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  1436 non-null   int64  
 1   Price       1436 non-null   int64  
 2   Age         1336 non-null   float64
 3   KM          1436 non-null   object 
 4   FuelType    1336 non-null   object 
 5   HP          1436 non-null   object 
 6   MetColor    1286 non-null   float64
 7   Automatic   1436 non-null   int64  
 8   CC          1436 non-null   int64  
 9   Doors       1436 non-null   object 
 10  Weight      1436 non-null   int64  
dtypes: float64(2), int64(5), object(4)
memory usage: 123.5+ KB
Mean for column MetColor is : 0.6749611197511665
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  1436 non-null   int64  
 1   Price       

**1.2.2. Replacing NULL data with median() value**

In [4]:
dataset = pd.read_csv('Exercise-CarData.csv') 
dataset.info()
print("Median for column MetColor is : " + str(dataset['MetColor'].median()))
dataset['MetColor']=dataset['MetColor'].fillna(dataset['MetColor'].mean())
dataset.info()
#dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  1436 non-null   int64  
 1   Price       1436 non-null   int64  
 2   Age         1336 non-null   float64
 3   KM          1436 non-null   object 
 4   FuelType    1336 non-null   object 
 5   HP          1436 non-null   object 
 6   MetColor    1286 non-null   float64
 7   Automatic   1436 non-null   int64  
 8   CC          1436 non-null   int64  
 9   Doors       1436 non-null   object 
 10  Weight      1436 non-null   int64  
dtypes: float64(2), int64(5), object(4)
memory usage: 123.5+ KB
Median for column MetColor is : 1.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  1436 non-null   int64  
 1   Price       1436 non-null

**1.2.3. Replacing NULL data with mode() value**

In [5]:
dataset = pd.read_csv('Exercise-CarData.csv') 
dataset.info()
print("Mode for column MetColor is : " + str(dataset['MetColor'].mode()))
dataset['MetColor']=dataset['MetColor'].fillna(dataset['MetColor'].mode())
dataset.info()
#dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  1436 non-null   int64  
 1   Price       1436 non-null   int64  
 2   Age         1336 non-null   float64
 3   KM          1436 non-null   object 
 4   FuelType    1336 non-null   object 
 5   HP          1436 non-null   object 
 6   MetColor    1286 non-null   float64
 7   Automatic   1436 non-null   int64  
 8   CC          1436 non-null   int64  
 9   Doors       1436 non-null   object 
 10  Weight      1436 non-null   int64  
dtypes: float64(2), int64(5), object(4)
memory usage: 123.5+ KB
Mode for column MetColor is : 0    1.0
dtype: float64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  1436 non-null   int64  
 1   Price  

**1.2.4. Replacing NULL data with standard deviation**

In [6]:
dataset = pd.read_csv('Exercise-CarData.csv') 
dataset.info()
print("Standard deviation for column MetColor is : " + str(dataset['MetColor'].std())) 
dataset['MetColor'] = dataset['MetColor'].fillna(dataset['MetColor'].std()) # standard deviation of that column
dataset.info()
#dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  1436 non-null   int64  
 1   Price       1436 non-null   int64  
 2   Age         1336 non-null   float64
 3   KM          1436 non-null   object 
 4   FuelType    1336 non-null   object 
 5   HP          1436 non-null   object 
 6   MetColor    1286 non-null   float64
 7   Automatic   1436 non-null   int64  
 8   CC          1436 non-null   int64  
 9   Doors       1436 non-null   object 
 10  Weight      1436 non-null   int64  
dtypes: float64(2), int64(5), object(4)
memory usage: 123.5+ KB
Standard deviation for column MetColor is : 0.4685715921911513
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  1436 non-null   int64  
 1 

## 2. Data Transformation

**2.1. Scaling (Min-Max Normalisation)**

In [11]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
datasets = pd.read_csv('Exercise-CarData.csv') 
print("\nData :\n",datasets)
# Any value which not match data's value format change it's formate according to it
dataset=dataset.replace(to_replace="??",value=55000)
# dataset
# Any value which not match data's value format change it's formate according to it
dataset=dataset.replace(to_replace="three",value=3)
# dataset
# Removes line which are not mandatory 
dataset.head(5)
X_new = dataset.iloc[:,1:4].values
print("\nX for transformation : \n", X_new)


Data :
       Unnamed: 0  Price   Age     KM FuelType   HP  MetColor  Automatic    CC  \
0              0  13500  23.0  46986   Diesel   90       1.0          0  2000   
1              1  13750  23.0  72937   Diesel   90       1.0          0  2000   
2              2  13950  24.0  41711   Diesel   90       NaN          0  2000   
3              3  14950  26.0  48000   Diesel   90       0.0          0  2000   
4              4  13750  30.0  38500   Diesel   90       0.0          0  2000   
...          ...    ...   ...    ...      ...  ...       ...        ...   ...   
1431        1431   7500   NaN  20544   Petrol   86       1.0          0  1300   
1432        1432  10845  72.0     ??   Petrol   86       0.0          0  1300   
1433        1433   8500   NaN  17016   Petrol   86       0.0          0  1300   
1434        1434   7250  70.0     ??      NaN   86       1.0          0  1300   
1435        1435   6950  76.0      1   Petrol  110       0.0          0  1600   

      Doors  Weigh

In [12]:
# performing scaling
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X_new)
print("\nScaled X : \n", X_scaled)



Scaled X : 
 [[0.3250444  0.27848101 0.19335471]
 [0.3339254  0.27848101 0.30014938]
 [0.3410302  0.29113924 0.1716468 ]
 ...
 [0.14742451        nan 0.07002086]
 [0.10301954 0.87341772 0.22633426]
 [0.09236234 0.94936709 0.        ]]


In [13]:
std = StandardScaler()
X_std = std.fit_transform(X_new)
print("\nStandardized X : \n", X_std)



Standardized X : 
 [[ 0.76376268 -1.75818903 -0.57923195]
 [ 0.83271485 -1.75818903  0.1193074 ]
 [ 0.88787659 -1.70437596 -0.72122243]
 ...
 [-0.6152808          nan -1.38595324]
 [-0.96004167  0.7710253  -0.36351408]
 [-1.04278428  1.09390373 -1.84395667]]


## 3. Handling Categorical Data

In [15]:
print(dataset)
dataset.describe()
# All rows, all columns except last 
X = dataset.iloc[:, :-1].values 
  
# Only last column  
Y = dataset.iloc[:, -1].values 

print("\n\nInput : \n", X) 
print("\n\nOutput: \n", Y) 

      Unnamed: 0  Price   Age     KM FuelType   HP  MetColor  Automatic    CC  \
0              0  13500  23.0  46986   Diesel   90  1.000000          0  2000   
1              1  13750  23.0  72937   Diesel   90  1.000000          0  2000   
2              2  13950  24.0  41711   Diesel   90  0.468572          0  2000   
3              3  14950  26.0  48000   Diesel   90  0.000000          0  2000   
4              4  13750  30.0  38500   Diesel   90  0.000000          0  2000   
...          ...    ...   ...    ...      ...  ...       ...        ...   ...   
1431        1431   7500   NaN  20544   Petrol   86  1.000000          0  1300   
1432        1432  10845  72.0  55000   Petrol   86  0.000000          0  1300   
1433        1433   8500   NaN  17016   Petrol   86  0.000000          0  1300   
1434        1434   7250  70.0  55000      NaN   86  1.000000          0  1300   
1435        1435   6950  76.0      1   Petrol  110  0.000000          0  1600   

     Doors  Weight  
0     

In [17]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
le = LabelEncoder()
X[ : ,0] = le.fit_transform(X[ : ,0])
print("\n\nInput : \n", X) 



Input : 
 [[0 13500 23.0 ... 0 2000 3]
 [1 13750 23.0 ... 0 2000 '3']
 [2 13950 24.0 ... 0 2000 '3']
 ...
 [1433 8500 nan ... 0 1300 '3']
 [1434 7250 70.0 ... 0 1300 '3']
 [1435 6950 76.0 ... 0 1600 '5']]


In [20]:
DatasetFuel = pd.get_dummies(dataset['FuelType'])
print("\nDatasetFuel :\n",DatasetFuel)
dataset = pd.concat([dummy,dataset],axis=1)
print("\n\nFinal Data :\n",dataset)


DatasetFuel :
       CNG  Diesel  Petrol
0       0       1       0
1       0       1       0
2       0       1       0
3       0       1       0
4       0       1       0
...   ...     ...     ...
1431    0       0       1
1432    0       0       1
1433    0       0       1
1434    0       0       0
1435    0       0       1

[1436 rows x 3 columns]


Final Data :
       CNG  Diesel  Petrol  Unnamed: 0  Price   Age     KM FuelType   HP  \
0       0       1       0           0  13500  23.0  46986   Diesel   90   
1       0       1       0           1  13750  23.0  72937   Diesel   90   
2       0       1       0           2  13950  24.0  41711   Diesel   90   
3       0       1       0           3  14950  26.0  48000   Diesel   90   
4       0       1       0           4  13750  30.0  38500   Diesel   90   
...   ...     ...     ...         ...    ...   ...    ...      ...  ...   
1431    0       0       1        1431   7500   NaN  20544   Petrol   86   
1432    0       0       1      

In [22]:
datasets=pd.read_csv('Exercise-CarData.csv')
onehotencoder = OneHotEncoder()
#reshape the 1-D country array to 2-D as fit_transform expects 2-D and finally fit the object 
x = onehotencoder.fit_transform(datasets.FuelType.values.reshape(-1,1)).toarray()
print(x)

ValueError: Input contains NaN