# Lab - 04 :

## Aim: Implement Linear Regression Algorithm on the given dataset

In [1]:
import numpy as np
import torch # It alows to use Torch which is same as Numpy but with strong GPU acceleration

In [2]:
x = torch.randn(3) # There are many functions like this which are supprted in Numpy supprted here as Well
print(x,'\n', x.shape, '\n') # torch uses tensor, which runs on GPU which is way more faster than CPU
npArray = np.array([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])
print(npArray)
tchArray = torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])
print(tchArray)

tensor([1.4388, 0.3829, 0.4142]) 
 torch.Size([3]) 

[[0.1 1.2]
 [2.2 3.1]
 [4.9 5.2]]
tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])


### Numpy to Torch Conversion

In [6]:
#Numpy to Torch Conversion DEMO
from numpy import random
a = random.rand(5)
b = torch.from_numpy(a)
print('a:',a)
print('b:',b)

a: [0.25240611 0.19808202 0.7682058  0.37594111 0.40831922]
b: tensor([0.2524, 0.1981, 0.7682, 0.3759, 0.4083], dtype=torch.float64)


### Taking Inputs

In [9]:
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
targets = np.array([[56], [81], [119], [22], [103]], dtype='float32')
print("Inputs : ", inputs)
print("Targets : ", targets)

Inputs :  [[ 73.  67.  43.]
 [ 91.  88.  64.]
 [ 87. 134.  58.]
 [102.  43.  37.]
 [ 69.  96.  70.]]
Targets :  [[ 56.]
 [ 81.]
 [119.]
 [ 22.]
 [103.]]


In [10]:
# Numpy to Torch Conversion
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [13]:
weight = torch.randn(2, 3, requires_grad=True)
bias = torch.randn(2, requires_grad=True)
print("Weight : ", weight)
print("Bias : ", bias)
print("Transpose of Weight : ", weight.t())
inputs @ weight.t() + bias

Weight :  tensor([[-1.3009,  1.1833, -0.5930],
        [-0.7427,  0.5476, -0.4383]], requires_grad=True)
Bias :  tensor([0.5785, 0.0550], requires_grad=True)
Transpose of Weight :  tensor([[-1.3009, -0.7427],
        [ 1.1833,  0.5476],
        [-0.5930, -0.4383]], grad_fn=<TBackward0>)


tensor([[ -40.6073,  -36.3244],
        [ -51.6278,  -47.3991],
        [  11.5636,  -16.6101],
        [-103.1736,  -68.3751],
        [ -17.0999,  -29.3085]], grad_fn=<AddBackward0>)

### Predicting for Model Inputs

In [15]:
def model(inputs):
    return inputs @ weight.t() + bias
prediction = model(inputs)
print("Prediction : ", prediction)

Prediction :  tensor([[ -40.6073,  -36.3244],
        [ -51.6278,  -47.3991],
        [  11.5636,  -16.6101],
        [-103.1736,  -68.3751],
        [ -17.0999,  -29.3085]], grad_fn=<AddBackward0>)


### Loss Function

In [22]:
diff0 = prediction - targets
torch.sum(diff0 * diff0) / diff0.numel()
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()
loss = mse(prediction, targets)
print(loss)

tensor(55.4095, grad_fn=<DivBackward0>)


### Compute Gradiants

In [17]:
loss.backward()
print(weight.grad)
print(bias.grad)

tensor([[ -9904.6055,  -9890.4932,  -6382.4038],
        [ -9713.9268, -10448.8730,  -6531.6719]])
tensor([-116.3890, -115.8035])


### Training the Model

In [18]:
with torch.no_grad():
    weight -= weight.grad * 1e-5
    bias -= bias.grad * 1e-5
    weight.grad.zero_()
    bias.grad.zero_()
prediction = model(inputs)
print("Prediction : ", prediction)
loss = mse(prediction, targets)
print("loss : ", loss)

Prediction :  tensor([[-24.0047, -19.4227],
        [-29.8251, -25.1830],
        [ 37.1368,   9.6320],
        [-86.4553, -51.5560],
        [  3.6980,  -8.0017]], grad_fn=<AddBackward0>)
loss :  tensor(9366.4600, grad_fn=<DivBackward0>)


In [21]:
for i in range(100):
    prediction = model(inputs)
    loss = mse(prediction, targets)
    loss.backward()
    with torch.no_grad():
        weight -= weight.grad * 1e-5
        bias -= bias.grad * 1e-5
        weight.grad.zero_()
        bias.grad.zero_()
prediction = model(inputs)
print("Prediction : ", prediction)
loss = mse(prediction, targets)
print("Loss : ", loss)
print("Target : ", targets)

Prediction :  tensor([[ 57.0037,  57.7207],
        [ 75.8432,  77.8955],
        [133.4277, 127.6056],
        [ 18.9402,  23.7781],
        [ 92.2153,  92.8586]], grad_fn=<AddBackward0>)
Loss :  tensor(55.4095, grad_fn=<DivBackward0>)
Target :  tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


# Linear regression using PyTorch built-ins

In [23]:
import numpy as np
import torch

In [25]:
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')
print("Inputs : ", inputs)
print("Targets : ", targets)

Inputs :  [[ 73.  67.  43.]
 [ 91.  88.  64.]
 [ 87. 134.  58.]
 [102.  43.  37.]
 [ 69.  96.  70.]]
Targets :  [[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]]


### Numpy to Torch Conversion

In [26]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print("Inputs : ", inputs)
print("Targets : ", targets)

Inputs :  tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
Targets :  tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


### Training Datasets

In [29]:
from torch.utils.data import TensorDataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

### Dataloads

In [30]:
from torch.utils.data import DataLoader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 87., 134.,  58.],
        [ 91.,  88.,  64.],
        [ 73.,  67.,  43.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[119., 133.],
        [ 81., 101.],
        [ 56.,  70.],
        [ 22.,  37.],
        [103., 119.]])


### nn.linear

In [31]:
import torch.nn as nn
model = nn.Linear(3, 2)
print("Model Weight : ", model.weight)
print("Model Bias : ", model.bias)
list(model.parameters())

Model Weight :  Parameter containing:
tensor([[-0.0576,  0.0383, -0.1267],
        [ 0.3958, -0.3731,  0.0301]], requires_grad=True)
Model Bias :  Parameter containing:
tensor([ 0.1621, -0.0466], requires_grad=True)


[Parameter containing:
 tensor([[-0.0576,  0.0383, -0.1267],
         [ 0.3958, -0.3731,  0.0301]], requires_grad=True),
 Parameter containing:
 tensor([ 0.1621, -0.0466], requires_grad=True)]

In [32]:
preds = model(inputs)
print("Preds : ", preds)

Preds :  tensor([[ -6.9175,   5.1456],
        [ -9.8083,   5.0673],
        [ -7.0540, -13.8595],
        [ -8.7473,  25.3992],
        [ -8.9950,  -6.4457]], grad_fn=<AddmmBackward0>)


### Loss Function

In [33]:
import torch.nn.functional as fun
loss_fn = fun.mse_loss
loss = loss_fn(model(inputs), targets)
print("Loss : ", loss)

Loss :  tensor(9243.0762, grad_fn=<MseLossBackward0>)


### Optimiser

In [34]:
opt = torch.optim.SGD(model.parameters(), lr=1e-5)
print(opt)

SGD (
Parameter Group 0
    dampening: 0
    lr: 1e-05
    momentum: 0
    nesterov: False
    weight_decay: 0
)


### Train for multiple epochs

In [40]:
def fit(num_epochs, model, loss_fn, opt, train_dl):
    # Repeat for given number of epochs
    for epoch in range(num_epochs):

        # Train with batches of data
        for xb,yb in train_dl:
            pred = model(xb) # Generate predictions
            loss = loss_fn(pred, yb) # Calculate loss
            loss.backward() # Compute gradients
            opt.step() # Update parameters using gradients
            opt.zero_grad() # Reset the gradients to zero
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch {}/{}, Loss: {:.6f}'.format(epoch+1, num_epochs, loss.item()))

In [41]:
fit(100, model, loss_fn, opt, train_dl)

Epoch 10/100, Loss: 75.176247
Epoch 20/100, Loss: 68.046486
Epoch 30/100, Loss: 61.734619
Epoch 40/100, Loss: 56.143627
Epoch 50/100, Loss: 51.188160
Epoch 60/100, Loss: 46.792892
Epoch 70/100, Loss: 42.891548
Epoch 80/100, Loss: 39.425812
Epoch 90/100, Loss: 36.344200
Epoch 100/100, Loss: 33.601463


In [42]:
prediction = model(inputs)
print("Prediction : ", prediction)
print("Targets : ", targets)

Prediction :  tensor([[ 58.5101,  72.2170],
        [ 80.2610,  99.1506],
        [120.9569, 133.3470],
        [ 28.4524,  47.8676],
        [ 94.2660, 110.1519]], grad_fn=<AddmmBackward0>)
Targets :  tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
