## Implement Naive Bayes classifier

### Weather Example  :

In [1]:
#DataSets
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB, MultinomialNB

weather = ['Sunny', 'Sunny', 'Overcast', 'Rainy', 'Rainy','Rainy', 'Overcast',
'Sunny', 'Sunny', 'Rainy', 'Sunny', 'Overcast', 'Overcast', 'Rainy']
temp = ['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild',
'Cool','Mild','Mild','Mild','Hot','Mild']
play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes',
'Yes','Yes','Yes','Yes','No']

In [2]:
#Encoding
le = preprocessing.LabelEncoder()
weather_encoded = le.fit_transform(weather)
temp_encoded = le.fit_transform(temp)
label = le.fit_transform(play)
print("Weather:" ,weather_encoded)
print("Temp:",temp_encoded)
print("Play:",label)

Weather: [2 2 0 1 1 1 0 2 2 1 2 0 0 1]
Temp: [1 1 1 2 0 0 0 2 0 2 2 2 1 2]
Play: [0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [3]:
#Combinig weather and temp into zip
features = tuple(zip(weather_encoded,temp_encoded))
print("Zip : ",features)

Zip :  ((2, 1), (2, 1), (0, 1), (1, 2), (1, 0), (1, 0), (0, 0), (2, 2), (2, 0), (1, 2), (2, 2), (0, 2), (0, 1), (1, 2))


In [4]:
#Create a Classifier & Training data
model = MultinomialNB()
model.fit(features,label)
print(model)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)


In [6]:
# Predicting the Output
# 0:Overcast, 2:Mild, 1:Hot, @:Sunny
predicted = model.predict([[0,2]]) # for Overcast and Mild
print("Prediction for Overcast & Mild : ", predicted)
predicted = model.predict([[0,1]]) # for Overcast and Hot
print("Prediction for Overcast & Hot : ", predicted)
predicted = model.predict([[2,2]]) # for Sunny and Mild
print("Prediction for Sunny & Mild : ", predicted)

Prediction for Overcast & Mild :  [1]
Prediction for Overcast & Hot :  [1]
Prediction for Sunny & Mild :  [1]


### Iris Classes (Ex-01) : 

In [11]:
import numpy as np
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB

#Load dataset
iris = datasets.load_iris()
print(iris)
# Print the names of Features
print("Features : ", iris.feature_names)
# Print the Labels
print("Labels : ", iris.target_names)
# print feature shape
print("Data shape : ",iris.data.shape)
# print target shape
print("Traget shape : ",iris.target.shape)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [12]:
#Reshaping the Data
newdata = iris.data[50:,:]
newtarget = iris.target[50:]
# print shape of Features data
print("New Data shape: ",newdata.shape)
# print shape of Target data
print("New Traget shape: ",newtarget.shape)

New Data shape:  (100, 4)
New Traget shape:  (100,)


In [14]:
# Splitting the training data
from sklearn.model_selection import train_test_split
#split data set into train and test sets
data_train, data_test, target_train, target_test = train_test_split(newdata,
newtarget, test_size = 0.30, random_state = 5)
print("Training data : ", data_train)
print("Testing data : ", data_test)
print("Training target : ", target_train)
print("Testing target : ", target_test)

Training data :  [[6.3 3.3 4.7 1.6]
 [6.  3.  4.8 1.8]
 [5.8 2.8 5.1 2.4]
 [6.8 2.8 4.8 1.4]
 [5.1 2.5 3.  1.1]
 [6.3 3.3 6.  2.5]
 [7.7 2.8 6.7 2. ]
 [6.5 3.  5.8 2.2]
 [6.1 2.8 4.  1.3]
 [6.6 3.  4.4 1.4]
 [6.  2.7 5.1 1.6]
 [5.7 2.6 3.5 1. ]
 [7.1 3.  5.9 2.1]
 [5.6 2.9 3.6 1.3]
 [7.7 3.  6.1 2.3]
 [7.2 3.  5.8 1.6]
 [6.7 3.  5.2 2.3]
 [5.5 2.3 4.  1.3]
 [5.  2.3 3.3 1. ]
 [5.9 3.  4.2 1.5]
 [6.2 3.4 5.4 2.3]
 [5.7 3.  4.2 1.2]
 [6.3 2.8 5.1 1.5]
 [7.7 3.8 6.7 2.2]
 [6.9 3.1 5.4 2.1]
 [6.3 3.4 5.6 2.4]
 [5.7 2.8 4.1 1.3]
 [6.4 2.8 5.6 2.2]
 [7.2 3.6 6.1 2.5]
 [5.6 2.5 3.9 1.1]
 [7.9 3.8 6.4 2. ]
 [5.6 3.  4.1 1.3]
 [7.7 2.6 6.9 2.3]
 [6.9 3.1 4.9 1.5]
 [5.5 2.4 3.7 1. ]
 [6.1 2.6 5.6 1.4]
 [5.8 2.7 5.1 1.9]
 [6.7 3.1 4.7 1.5]
 [6.5 2.8 4.6 1.5]
 [7.  3.2 4.7 1.4]
 [6.7 2.5 5.8 1.8]
 [5.7 2.8 4.5 1.3]
 [6.3 2.5 5.  1.9]
 [6.4 3.2 4.5 1.5]
 [6.8 3.2 5.9 2.3]
 [6.1 3.  4.6 1.4]
 [5.2 2.7 3.9 1.4]
 [6.2 2.2 4.5 1.5]
 [6.9 3.1 5.1 2.3]
 [6.2 2.9 4.3 1.3]
 [6.4 3.2 5.3 2.3]
 [7.2 3.2 6.  

In [15]:
# Training the Datasets
import numpy as np
gnb = GaussianNB()
#Train the model using the training sets
gnb.fit(data_train, target_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [17]:
#Predict the response for test dataset
target_pred = gnb.predict(data_test)
print(target_pred)

[2 1 1 1 2 1 1 2 1 1 2 1 2 1 2 1 1 2 1 1 2 1 1 1 1 1 2 2 2 2]


In [25]:
# Calculating accuracy
from sklearn import metrics
print("Accuracy : ",metrics.accuracy_score(target_test, target_pred))

Accuracy :  0.9


In [26]:
#Import confusion_matrix for confusion_matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)

array([[16,  1],
       [ 2, 11]])

In [30]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred)
recall = recall_score(target_test, target_pred)
print('precision : {}'.format(precision))
print('recall : {}'.format(recall))

precision: 0.8888888888888888
recall: 0.9411764705882353


### Iris Classes (Ex-02) : 

In [32]:
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
#Load dataset
iris = datasets.load_iris()

# print the names of features
print("Features: ", iris.feature_names)
# print the labels
print("Labels: ", iris.target_names)
# print data(feature)shape
print(iris.data.shape)

Features:  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Labels:  ['setosa' 'versicolor' 'virginica']
(150, 4)


In [33]:
# Splling the data for Training
from sklearn.model_selection import train_test_split

#split data set into train and test sets
data_train, data_test, target_train, target_test = train_test_split(iris.data, iris.target, test_size = 0.30, random_state = 10)
print("Training data : ", data_train)
print("Testing data : ", data_test)
print("Training target : ", target_train)
print("Testing target : ", target_test)

Training data :  [[5.2 4.1 1.5 0.1]
 [6.9 3.1 4.9 1.5]
 [5.9 3.2 4.8 1.8]
 [5.6 2.8 4.9 2. ]
 [6.7 3.3 5.7 2.5]
 [6.2 2.2 4.5 1.5]
 [7.2 3.6 6.1 2.5]
 [5.5 2.4 3.7 1. ]
 [6.  2.9 4.5 1.5]
 [6.4 3.2 4.5 1.5]
 [5.8 4.  1.2 0.2]
 [5.3 3.7 1.5 0.2]
 [6.1 2.9 4.7 1.4]
 [5.4 3.4 1.7 0.2]
 [6.4 3.1 5.5 1.8]
 [4.7 3.2 1.6 0.2]
 [4.6 3.1 1.5 0.2]
 [4.9 2.5 4.5 1.7]
 [5.1 2.5 3.  1.1]
 [6.7 3.1 5.6 2.4]
 [4.9 3.6 1.4 0.1]
 [6.9 3.1 5.4 2.1]
 [4.8 3.  1.4 0.3]
 [5.8 2.7 3.9 1.2]
 [6.  2.7 5.1 1.6]
 [4.4 3.2 1.3 0.2]
 [6.8 3.2 5.9 2.3]
 [7.9 3.8 6.4 2. ]
 [6.5 3.  5.5 1.8]
 [7.6 3.  6.6 2.1]
 [6.3 2.8 5.1 1.5]
 [4.6 3.4 1.4 0.3]
 [5.7 2.6 3.5 1. ]
 [6.7 2.5 5.8 1.8]
 [5.7 2.8 4.1 1.3]
 [4.9 3.1 1.5 0.2]
 [6.4 2.8 5.6 2.1]
 [7.  3.2 4.7 1.4]
 [5.7 2.9 4.2 1.3]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [5.1 3.8 1.9 0.4]
 [5.4 3.  4.5 1.5]
 [7.4 2.8 6.1 1.9]
 [6.3 2.9 5.6 1.8]
 [6.6 3.  4.4 1.4]
 [5.  3.4 1.5 0.2]
 [5.1 3.8 1.6 0.2]
 [5.1 3.5 1.4 0.3]
 [6.5 3.  5.8 2.2]
 [5.8 2.7 5.1 1.9]
 [6.1 2.8 4.  

In [34]:
import numpy as np
gnb = GaussianNB()
#Training the model using the training sets
gnb.fit(data_train, target_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [35]:
#Predict the response for test dataset
target_pred = gnb.predict(data_test)
print(target_pred)

[1 2 0 1 0 1 1 1 0 1 1 2 1 0 0 2 1 0 0 0 2 2 2 0 1 0 1 1 1 2 1 1 2 2 2 0 2
 2 2 2 0 0 1 0 1]


In [36]:
# Calculating accuracy
from sklearn import metrics
print("Accuracy : ",metrics.accuracy_score(target_test, target_pred))

Accuracy :  1.0


In [37]:
#Import confusion_matrix for confusion_matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)

array([[14,  0,  0],
       [ 0, 17,  0],
       [ 0,  0, 14]])

In [38]:
# Finding the precision
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)
print('precision : {}'.format(precision))
print('recall : {}'.format(recall))

precision : [1. 1. 1.]
recall : [1. 1. 1.]


### NB Classifier Exercise

In [2]:
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB

iris = datasets.load_iris()
print("Labels : ", iris.target_names)
print("Features : ", iris.feature_names)
print("Iris Data shape : ", iris.data.shape)

Labels :  ['setosa' 'versicolor' 'virginica']
Features :  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Iris Data shape :  (150, 4)


In [3]:
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB, MultinomialNB
import pandas as pd
import numpy as np 

In [4]:
# Loading Data
        
datasets = pd.read_csv('Dataset1.csv')
Outlook = datasets['Outlook']
Humidity = datasets['Humidity']
Wind = datasets['Wind']
Play = datasets['Play']
Temp = datasets['Temp']
print("Wind : ", Wind)
print("Play : ", Play)
print("Temp : ", Temp)

Wind :  0     F
1     T
2     F
3     F
4     F
5     T
6     T
7     F
8     F
9     F
10    T
11    T
12    F
13    T
Name: Wind, dtype: object
Play :  0     N
1     N
2     Y
3     Y
4     Y
5     N
6     Y
7     N
8     Y
9     Y
10    Y
11    Y
12    Y
13    N
Name: Play, dtype: object
Temp :  0     H
1     H
2     H
3     M
4     C
5     C
6     C
7     M
8     C
9     M
10    M
11    M
12    H
13    M
Name: Temp, dtype: object


In [5]:
# Encoding 
le = preprocessing.LabelEncoder()

Outlook_encoded=le.fit_transform(Outlook)
print("Outlook:" ,Outlook_encoded)

Humidity_encoded=le.fit_transform(Humidity)
print("Humidity:" ,Humidity_encoded)

Wind_encoded=le.fit_transform(Wind)
print("Wind:" ,Wind_encoded)

Play_encoded=le.fit_transform(Play)
print("Play:" ,Play_encoded)

Temp_encoded=le.fit_transform(Temp)
print("Temp:" ,Temp_encoded)

Outlook: [1 1 0 2 2 2 0 1 1 2 1 0 0 2]
Humidity: [2 0 2 2 2 1 2 2 1 0 0 1 2 2]
Wind: [0 1 0 0 0 1 1 0 0 0 1 1 0 1]
Play: [0 0 1 1 1 0 1 0 1 1 1 1 1 0]
Temp: [1 1 1 2 0 0 0 2 0 2 2 2 1 2]


In [6]:
features=tuple(zip(Humidity_encoded,Outlook_encoded,Temp_encoded,Wind_encoded))
print("Features : ",features)

Features :  ((2, 1, 1, 0), (0, 1, 1, 1), (2, 0, 1, 0), (2, 2, 2, 0), (2, 2, 0, 0), (1, 2, 0, 1), (2, 0, 0, 1), (2, 1, 2, 0), (1, 1, 0, 0), (0, 2, 2, 0), (0, 1, 2, 1), (1, 0, 2, 1), (2, 0, 1, 0), (2, 2, 2, 1))


In [7]:
# Train the model using the training sets
model = MultinomialNB()
model.fit(features,Play)
print(model)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)


In [10]:
predicted = model.predict([[1,1,0,0]])#[[HUMIDITY=2,OUTLOOK=1,TEMP=2,WIND=0]] 
print("Prediction : ", predicted) 

Prediction :  ['Y']


In [11]:
# Splling the data for Training
from sklearn.model_selection import train_test_split
data_train, data_test, target_train, target_test = train_test_split(features, Play, test_size = 0.20, random_state =11)
print("Training data : ", data_train)
print("Testing data : ", data_test)
print("Training target : ", target_train)
print("Testing target : ", target_test)

Training data :  [(1, 2, 0, 1), (2, 2, 0, 0), (2, 0, 1, 0), (2, 0, 1, 0), (2, 2, 2, 1), (0, 1, 2, 1), (2, 1, 2, 0), (0, 1, 1, 1), (1, 0, 2, 1), (2, 1, 1, 0), (0, 2, 2, 0)]
Testing data :  [(2, 0, 0, 1), (2, 2, 2, 0), (1, 1, 0, 0)]
Training target :  5     N
4     Y
12    Y
2     Y
13    N
10    Y
7     N
1     N
11    Y
0     N
9     Y
Name: Play, dtype: object
Testing target :  6    Y
3    Y
8    Y
Name: Play, dtype: object


In [12]:
import numpy as np
gnb = GaussianNB()
#Training the model using the training sets
gnb.fit(data_train, target_train)
#Predict the response for test dataset
target_pred = gnb.predict(data_test)
print(target_pred)

['Y' 'N' 'Y']


In [13]:
from sklearn import metrics
# Calculating accuracy
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 0.6666666666666666


In [14]:
#Import confusion_matrix for confusion_matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)

array([[0, 0],
       [1, 2]])

In [16]:
# Finding the precision
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [0. 1.]
recall: [0.         0.66666667]
